   name: Deploy to InfinityFree

   on:
     push:
       branches:
         - main

   jobs:
     deploy:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        
        - name: Run AI 自動筆 script
          run: python commit.py
        
        - uses: stefanzweifel/git-auto-commit-action@v5
          id: auto-commit-action
          with:
             commit_message: Changed files
             branch: ${{ github.ref }}
             force: true
        
        - name: Setup FTP deployment
          uses: SamKirkland/FTP-Deploy-Action@4.3.0
          env:
             FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
             FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          with:
             server: ftpupload.net
             username: ${{ secrets.FTP_USERNAME }}
             password: ${{ secrets.FTP_PASSWORD }}
             local-dir: ./ 
             server-dir: /htdocs/
             exclude: .git* **/.git* **/.github* 
